<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-GSB1S88" failures="2" tests="2" name="Test(failed)" time="0.117" errors="0" timestamp="2022-07-25T09:58:15 IST">
  <testcase classname="RetryFaildTestCases.FaildTestCases" name="TestCases02" time="0.021">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at RetryFaildTestCases.FaildTestCases.TestCases02(FaildTestCases.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCases02 -->
  <testcase classname="RetryFaildTestCases.FaildTestCases" name="TestCases01" time="0.002">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at RetryFaildTestCases.FaildTestCases.TestCases01(FaildTestCases.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCases01 -->
  <testcase classname="RetryFaildTestCases.FaildTestCases" name="TestCases03" time="0.0">
    <ignored/>
  </testcase> <!-- TestCases03 -->
</testsuite> <!-- Test(failed) -->
